### ISSUE TITLE
Windows GPU not found

### ISSUE THREAD

**Issue by imanrep** [ngirot/BruteForce#11]
i have `go env CGO_CPPFLAGS` with result `-I c:\OCL_SDK_Light\include` and
`go env CGO_LDFLAGS` with result `-L c:\OCL_SDK_Light\lib\x86_64` but if im using --gpu it said No GPU found (when searching device with OpenCl compatibility)

**Comment by imanrep** [comment]
it said `# gitlab.com/ngirot/blackcl
cgo-gcc-prolog: In function '_cgo_31feb7a9f85f_Cfunc_clCreateCommandQueue':
cgo-gcc-prolog:55:2: warning: 'clCreateCommandQueue' is deprecated [-Wdeprecated-declarations]
In file included from ..\..\..\..\go\pkg\mod\gitlab.com\ngirot\blackcl@v0.0.0-20220921204859-5c4334c7e4e0\blackcl.go:13:
c:\OCL_SDK_Light\include/CL/cl.h:1359:1: note: declared here
 clCreateCommandQueue(cl_context                     /* context */,
 ^~~~~~~~~~~~~~~~~~~~`

when i tried go build -tags opencl

**Comment by ngirot** [comment]
Hello,

You don't have to use CGO_CPPFLAGS and CGO_LDFLAGS to run the app, only to built it.

At runtime: first you must be sure that your GPU and the driver supports OpenCL. That said, i fixed a GPU detection issue in the last version, so be sure to use the 1.4.

At compile time:  the warning you see is from the cl.h from ocl-sdk, it will not break the compilation and it's fine.
The error you have is during link phase, it looks like the linker don't find the OpenCL.lib file (the CGO_LDFLAGS part). I'm not using minw32 so I don't really know the toolchain... Maybe minw32 is for 32 bit only and you should use `c:\OCL_SDK_Light\lib\x86` instead of `c:\OCL_SDK_Light\lib\x86_64`
