### ISSUE TITLE
add gpu support

### ISSUE THREAD

**Issue by Ladif1** [ngirot/BruteForce#6]
is it possible ?

**Comment by ngirot** [comment]
I think it is possible. I'm not an expert about GPU so I'm not sure it will work with the current software architecture.
I will try as soon as I have dome free time to work on it.

**Comment by Ladif1** [comment]
nice thanks you very much

**Comment by ngirot** [comment]
I tried to work on a first version with GPU support, it only support SHA-256 and windows/linux.

Performance with --dictionary option are better, but not with the --alphabet (default). So I don't know if it's because my GPU is really bad or if I need to work on optimizations (or maybe a different way to implements this)

If you have a good GPU, maybe you can give it a shot and tell me your results. 

You can try to download a version on https://github.com/ngirot/BruteForce/releases/tag/1.3-beta
And the documentation and the code is on the 'gpu' branch: https://github.com/ngirot/BruteForce/tree/gpu

**Comment by Ladif1** [comment]
Hi, thanks you for working on that

![image](https://user-images.githubusercontent.com/42867072/115473788-9f57c900-a23c-11eb-8043-42818d35a2c5.png)
 
This is what I get with my RTX 3080 with "test" but in Task Manager it's still showing that the CPU is using aswell, is it normal ?

**Comment by ngirot** [comment]
Yes, on this first version, the code generating the words to test is still on the CPU (but only one core, instead of all of them for the CPU version).

Based on your screenshot, it looks like it's the bottleneck, which is not the case on my GPU, so, I will work on that for next version.

Thank you for your feedback.

**Comment by ngirot** [comment]
OK, new version. The workload generation words is partially deported to GPU now, it's faster, and my GPU usage is now 100%.
I want to keep displaying current status to user, so I can't fully deport that code. I currently send the workload by batch of ~500k words to generate by the GPU, so maybe it need to auto-adapt of better/worse GPU...

Anyway, I hope it gives better with your great 3080 !

You can download this new version at : https://github.com/ngirot/BruteForce/releases/tag/untagged-f4143d6978232f774c7e
Code and documentation still available at the same place.
